--Creo la tabella del tipo dei post
CREATE TABLE postType(
    postTypeID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32)
);

--Creo la tabella degli utenti
CREATE TABLE users(
    userID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    surname VARCHAR (32) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(128) NOT NULL,
    url VARCHAR(1024),
    birthday VARCHAR(35),
    status VARCHAR (1024)
);

--Creo la tabella degli amministratori.
CREATE TABLE administrators(
   adminID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   adminUser INTEGER,
   FOREIGN KEY (adminUser) REFERENCES users(userID)
);


--Creo la tabella dei post verso altri utenti
CREATE TABLE userPosts(
    postID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(500) NOT NULL,
    type INTEGER, 
    FOREIGN KEY (type) REFERENCES postType(postTypeID),
    author INTEGER,
    FOREIGN KEY (author) REFERENCES users(userID),
    toUser INTEGER,
    FOREIGN KEY (toUser) REFERENCES users(userID),
    attachment VARCHAR(1024)
    
);


--Creo la tabella dei gruppi:
CREATE TABLE groups(
    groupID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    icon VARCHAR(300),
    founder INTEGER,
    FOREIGN KEY (founder) REFERENCES users(userID)
);

--Creo la tabella dei post dei gruppi
CREATE TABLE groupPosts(
    postID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(500) NOT NULL,
    type INTEGER, 
    FOREIGN KEY (type) REFERENCES postType(postTypeID),
    author INTEGER,
    FOREIGN KEY (author) REFERENCES users(userID),
    toGroup INTEGER,
    FOREIGN KEY (toGroup) REFERENCES groups(groupID),
    attachment VARCHAR(1024)
    
);


--Creo tabella per gli amici
CREATE TABLE friends(
   follower INTEGER,
   followed INTEGER,
   FOREIGN KEY (follower) REFERENCES users(userID),
   FOREIGN KEY (followed) REFERENCES users(userID),
   PRIMARY KEY (follower, followed)
);

--Creo tabella per i partecipanti dei gruppi:
CREATE TABLE teams(
   joiner INTEGER,
   team INTEGER,
   FOREIGN KEY (joiner) REFERENCES users(userID),
   FOREIGN KEY (team) REFERENCES groups(groupID),
   PRIMARY KEY (joiner, team)
);